package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/pkerspe/terraform-provider-databasus/internal/client"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &StorageS3Resource{}
var _ resource.ResourceWithImportState = &StorageS3Resource{}

func NewStorageS3Resource() resource.Resource {
	return &StorageS3Resource{}
}

// StorageS3Resource defines the resource implementation.
type StorageS3Resource struct {
	client *client.DatabasusClient
}

func (r *StorageS3Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_storage_s3"
}

func (r *StorageS3Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "S3 Storage resource",

		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the storage to be created",
				Required:            true,
			},
			"workspace_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The id of the workspace the storage belongs to",
			},
			"is_system": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "isSystem flag from databasus (no description available in Databasus REST API)",
			},
			"s3_access_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The S3 access key",
			},
			"s3_secret_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The S3 secret key",
			},
			"s3_bucket": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The bucket name",
			},
			"s3_endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Custom S3-compatible endpoint URL (optional, leave empty for AWS S3)",
			},
			"s3_prefix": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional prefix for all object keys (e.g., 'backups/' or 'my_team/'). May not work with some S3-compatible storages. Cannot be changed after creation (otherwise backups will be lost)",
			},
			"s3_region": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The S3 region string",
			},
			"s3_storage_class": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "S3 storage class for uploaded objects. Leave empty to use Standard storage class. Some providers offer cheaper classes like One Zone IA. Do not use Glacier/Deep Archive — files must be immediately accessible for restores",
			},
			"s3_use_virtual_hosted_style": schema.BoolAttribute{
				Required:            true,
				MarkdownDescription: "Use virtual-hosted-style URLs (bucket.s3.region.amazonaws.com) instead of path-style (s3.region.amazonaws.com/bucket). May be required if you see COS errors",
			},
			"skip_tls_verify": schema.BoolAttribute{
				Required:            true,
				MarkdownDescription: "Skip TLS certificate verification. Enable this if your S3-compatible storage uses a self-signed certificate. Warning: this reduces security",
			},
			"storage_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "",
			},
			"last_save_error": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "lastSaveError value generated by databasus (API description unclear)",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The internal Id of the Storage Configuration",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *StorageS3Resource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.DatabasusClient)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.DatabasusClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *StorageS3Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan client.StorageS3ResourceModel
	diags := req.Plan.Get(ctx, &plan)

	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create new S3Storage Configuration
	result, err := r.client.CreateStorageS3(ctx, plan)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating S3 Storage",
			"Could not create S3 Storage, unexpected error: "+err.Error(),
		)
		return
	}

	tflog.Trace(ctx, "created new S3 Storage resource")

	// Set state to fully populated data
	client.MapResponseToStorageS3ResourceModel(result, &plan)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *StorageS3Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data client.StorageS3ResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.GetStorageS3(ctx, data.Id.ValueString())
	if err != nil {
		// The Databasus RETS API returns currently an wrong RC 400 in case of te Record not found
		// Terraform expects an empty return in that case without an error in the diagnostics
		// see also https://github.com/databasus/databasus/issues/529
		if err.IsNotFound() {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("API Error", err.Error())
		return
	}

	// Set state to fully populated data
	client.MapResponseToStorageS3ResourceModel(result, &data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *StorageS3Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data client.StorageS3ResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Update existing workspace
	result, err := r.client.UpdateStorageS3(ctx, data.Id.ValueString(), data)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating S3 Storage",
			"Could not update S3 Storage, unexpected error: "+err.Error(),
		)
		return
	}

	// Set state to fully populated data
	client.MapResponseToStorageS3ResourceModel(result, &data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *StorageS3Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state client.StorageS3ResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteStorageS3(ctx, state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error deleting S3 Storage Configuration", "Could not delete S3 Storage, unexpected error: "+err.Error())
		return
	}
}

func (r *StorageS3Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
