// Copyright (c) pkerspe
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/pkerspe/terraform-provider-databasus/internal/client"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &NotifierWebhookResource{}
var _ resource.ResourceWithImportState = &NotifierWebhookResource{}

func NewNotifierWebhookResource() resource.Resource {
	return &NotifierWebhookResource{}
}

// NotifierWebhookResource defines the resource implementation.
type NotifierWebhookResource struct {
	client *client.DatabasusClient
}

func (r *NotifierWebhookResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notifier_webhook"
}

func (r *NotifierWebhookResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "Webhook Notifier resource to create/manage notifiers that trigger a webhook / URL",

		//"notifierType": "WEBHOOK"

		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the storage to be created",
				Required:            true,
			},
			"workspace_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The id of the workspace the storage belongs to",
			},
			"last_save_error": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "lastSaveError value generated by databasus (API description unclear)",
			},
			"body_template": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The template string for the request body to be sent to the webhook URL. Supported pLaceholders are '{{heading}}' and '{{message}}'.",
			},
			"headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "Map of headers to send. Header name is the key and 'value' is the header value. NOTE: headers could contain sensitive values which, even though marked as sensitive, are stored unencrypted in the state file",
			},
			"webhook_method": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The HTTP method to use, in most cases POST",
			},
			"webhook_url": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The full URL to send the notification to",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The internal Id of the Storage Configuration",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *NotifierWebhookResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.DatabasusClient)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.DatabasusClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *NotifierWebhookResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan client.NotifierWebhookResourceModel
	diags := req.Plan.Get(ctx, &plan)

	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create new LocalStorage Configuration
	result, err := r.client.CreateNotifierWebhook(ctx, plan)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Webhook Notifier",
			"Could not create Webhook Notifier, unexpected error: "+err.Error(),
		)
		return
	}

	tflog.Trace(ctx, "created new Webhook Notifier resource")

	// Set state to fully populated data
	client.MapResponseToNotifierWebhookResourceModel(ctx, result, &plan)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *NotifierWebhookResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data client.NotifierWebhookResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.GetNotifierWebhook(ctx, data.Id.ValueString())
	if err != nil {
		// The Databasus RETS API returns currently an wrong RC 400 in case of te Record not found
		// Terraform expects an empty return in that case without an error in the diagnostics
		// see also https://github.com/databasus/databasus/issues/529
		if err.IsNotFound() {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("API Error", err.Error())
		return
	}

	// Set state to fully populated data
	client.MapResponseToNotifierWebhookResourceModel(ctx, result, &data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *NotifierWebhookResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data client.NotifierWebhookResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Update existing workspace
	result, err := r.client.UpdateNotifierWebhook(ctx, data.Id.ValueString(), data)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating Webhook Notifier",
			"Could not update Webhook Notifier, unexpected error: "+err.Error(),
		)
		return
	}

	// Set state to fully populated data
	client.MapResponseToNotifierWebhookResourceModel(ctx, result, &data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *NotifierWebhookResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state client.NotifierWebhookResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteNotifierWebhook(ctx, state.Id.ValueString())
	if err != nil {
		// The Databasus RETS API returns currently an wrong RC 400 in case of te Record not found
		// Terraform expects an empty return in that case without an error in the diagnostics
		// see also https://github.com/databasus/databasus/issues/529
		if err.IsNotFound() {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error deleting Webhook Notifier Configuration", "Could not delete Webhook Notifier, unexpected error: "+err.Error())
		return
	}
}

func (r *NotifierWebhookResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
